import chalk from 'chalk';
import { existsSync, writeFileSync, unlinkSync, chmodSync, readFileSync } from 'fs';
import { join } from 'path';
import { isInitialized } from '../utils/config.js';

const HOOK_MARKER = '# vibelog-auto-hook';

function getHookPath(): string {
  return join(process.cwd(), '.git', 'hooks', 'post-commit');
}

const HOOK_SCRIPT = `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by VibeLog - logs every commit automatically
# Remove with: vibe hooks remove

COMMIT_MSG=$(git log -1 --pretty=%s)
npx vibelog log "$COMMIT_MSG" --auto 2>/dev/null || true
`;

export async function hooksInstallCommand(): Promise<void> {
  if (!isInitialized()) {
    console.log(chalk.red('❌ VibeLog not initialized. Run `vibe init` first.'));
    process.exit(1);
  }

  const gitDir = join(process.cwd(), '.git');
  if (!existsSync(gitDir)) {
    console.log(chalk.red('❌ Not a git repository. Initialize git first.'));
    process.exit(1);
  }

  const hooksDir = join(gitDir, 'hooks');
  if (!existsSync(hooksDir)) {
    const { mkdirSync } = await import('fs');
    mkdirSync(hooksDir, { recursive: true });
  }

  const hookPath = getHookPath();

  // Check for existing hook
  if (existsSync(hookPath)) {
    const existing = readFileSync(hookPath, 'utf-8');
    if (existing.includes(HOOK_MARKER)) {
      console.log(chalk.yellow('⚠️  VibeLog hook already installed.'));
      return;
    }
    // Append to existing hook
    writeFileSync(hookPath, existing + '\n' + HOOK_SCRIPT);
    console.log(chalk.green('✅ VibeLog hook appended to existing post-commit hook.'));
  } else {
    writeFileSync(hookPath, HOOK_SCRIPT);
    console.log(chalk.green('✅ Git post-commit hook installed!'));
  }

  try {
    chmodSync(hookPath, 0o755);
  } catch {
    // chmod may fail on Windows, hook still works
  }

  console.log(chalk.gray('   Every commit will now auto-log to VibeLog.'));
  console.log(chalk.gray('   Remove with: vibe hooks remove'));
}

export async function hooksRemoveCommand(): Promise<void> {
  const hookPath = getHookPath();

  if (!existsSync(hookPath)) {
    console.log(chalk.yellow('⚠️  No post-commit hook found.'));
    return;
  }

  const content = readFileSync(hookPath, 'utf-8');
  if (!content.includes(HOOK_MARKER)) {
    console.log(chalk.yellow('⚠️  Post-commit hook exists but was not created by VibeLog.'));
    return;
  }

  // If the hook only contains our script, remove the file
  const lines = content.split('\n');
  const nonVibeLines = lines.filter(
    line => !line.includes(HOOK_MARKER) &&
            !line.includes('vibelog-auto-hook') &&
            !line.includes('Auto-generated by VibeLog') &&
            !line.includes('Remove with: vibe hooks remove') &&
            !line.includes('npx vibelog log') &&
            !line.includes('COMMIT_MSG=$(git log')
  ).filter(line => line.trim() !== '' && line.trim() !== '#!/bin/sh');

  if (nonVibeLines.length === 0) {
    unlinkSync(hookPath);
    console.log(chalk.green('✅ VibeLog post-commit hook removed.'));
  } else {
    // Remove only our lines
    const cleaned = content
      .split(HOOK_MARKER)[0]
      .trimEnd() + '\n';
    writeFileSync(hookPath, cleaned);
    console.log(chalk.green('✅ VibeLog hook removed (other hooks preserved).'));
  }
}
